[package]
name = "szalinski-egg"
version = "0.1.0"
authors = ["Max Willsey <me@mwillsey.com>"]
edition = "2018"


[dependencies]
log = "0.4"
ordered-float = "1"
symbolic_expressions = "5.0.3"
smallvec = "0.6"
indexmap = "1"

[dependencies.egg]
git = "https://github.com/mwillsey/egg.git"
rev = "db6d79ee561d9789350909b3688e811ea2ebd16b"
# path = "/home/mwillsey/src/egg/egg"

[dev-dependencies]
env_logger = "0.6"
