[package]
name = "szalinski-egg"
version = "0.1.0"
authors = ["Max Willsey <me@mwillsey.com>"]
edition = "2018"


[dependencies]
log = "0.4"
ordered-float = "1"
symbolic_expressions = "5.0.3"
strum = "0.15"
strum_macros = "0.15"
smallvec = "0.6"

[dependencies.egg]
git = "https://github.com/mwillsey/egg.git"
rev = "fd963c48ba08ef4ee84b694ca1e5500cccb5107c"

[dev-dependencies]
env_logger = "0.6"
