[package]
name = "szalinski-egg"
version = "0.1.0"
authors = ["Max Willsey <me@mwillsey.com>"]
edition = "2018"


[dependencies]
log = "0.4"
ordered-float = "1"
symbolic_expressions = "5.0.3"
smallvec = "0.6"
indexmap = "1"
permutation = "0.2.5"

[dependencies.egg]
git = "https://github.com/mwillsey/egg.git"
rev = "ece7bdfb4d818fcf4f31eb5af3a0dfffb8c4e371"
# path = "/home/mwillsey/src/egg/egg"

[dev-dependencies]
env_logger = "0.6"
colored-diff = "0.2"
