[package]
name = "szalinski-egg"
version = "0.1.0"
authors = ["Max Willsey <me@mwillsey.com>"]
edition = "2018"


[dependencies]
log = "0.4"
ordered-float = "1"
symbolic_expressions = "5.0.3"
smallvec = "0.6"

[dependencies.egg]
git = "https://github.com/mwillsey/egg.git"
rev = "4677c90a42b2eef0fd859a9ee246b0d1d25463dd"
# path = "/home/mwillsey/src/egg/egg"

[dev-dependencies]
env_logger = "0.6"
